name: dash_kit_loadable
description: Widgets for displaying different request states without additional code.
version: 1.0.4
homepage: https://github.com/Dash-Kit/dash-kit-loadable

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dash_kit_core:
    git:
      url: git://github.com/Dash-Kit/dash-kit-core
      ref: asyc_redux

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
