name: dash_kit_loadable
description: Widgets for displaying different request states without additional code.
version: 3.0.0-dev.1
homepage: https://github.com/Dash-Kit/dash-kit-loadable

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dash_kit_core: ^3.0.0-dev.2
    
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
